"""
app.py
======
Streamlit web application demonstrating **Headless Bob** integration.

This application provides a chat-style UI that connects to a running
Headless Bob service (https://github.com/ibm-self-serve-assets/building-blocks/
tree/main/ai/ai-engineering/headless-bob) via its REST API.

Features demonstrated:
  - Listing and creating conversation threads (persistent conversation lifecycle)
  - Sending prompts to IBM Bob Shell via REST POST /api/v1/threads/{id}/messages
    Note: the message API only accepts {"content": <string>}.  Extra fields
    (including a ``mode`` parameter) cause a 400 Bad Request.  The selected
    mode is therefore prepended to the prompt as "[Mode: <name>] <prompt>"
    when a non-default mode is chosen.
  - Streaming live SSE output — events are typed as ``message.part``,
    ``message.completed``, ``run.completed``, and ``run.failed``
  - Viewing run metadata (duration, tokens, tool calls)
  - Browsing and downloading workspace files generated by Bob
  - Checking server capabilities

Usage:
    streamlit run src/app.py
"""

import os
import time
import threading
from datetime import datetime, timezone
from pathlib import Path

import streamlit as st
from dotenv import load_dotenv

# Load .env from the project root (one directory above src/)
_ROOT = Path(__file__).resolve().parent.parent
load_dotenv(_ROOT / ".env")

# Import our Headless Bob client module
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
import headless_bob_client as hb

# ---------------------------------------------------------------------------
# Page configuration
# ---------------------------------------------------------------------------

st.set_page_config(
    page_title="Headless Bob Demo",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------------
# Session state helpers
# ---------------------------------------------------------------------------

def _init_state() -> None:
    """Initialize all Streamlit session state keys on first load."""
    defaults = {
        "active_thread_id": None,
        "active_thread_title": "",
        "threads": [],
        "chat_history": [],   # list of {"role": str, "content": str, "meta": dict}
        "streaming_text": "",
        "run_meta": None,
        "last_error": "",
        "capabilities": None,
        "workspace_files": [],
    }
    for key, value in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = value


_init_state()

# ---------------------------------------------------------------------------
# Sidebar — service status & thread management
# ---------------------------------------------------------------------------

st.sidebar.title("🤖 Headless Bob")
st.sidebar.caption("IBM Bob Shell as a REST service")

# Connection status badge
try:
    if st.session_state.capabilities is None:
        st.session_state.capabilities = hb.get_capabilities()
    caps = st.session_state.capabilities
    st.sidebar.success(
        f"✅ Connected  \n"
        f"Service v{caps.version} · Bob {caps.bob_version}  \n"
        f"Concurrency: {caps.max_concurrent} · Queue: {caps.max_queued}"
    )
except EnvironmentError as exc:
    st.sidebar.error(f"⚠️ Not configured: {exc}")
    st.sidebar.info("Set HEADLESS_BOB_URL and HEADLESS_BOB_TOKEN in .env")
    st.stop()
except Exception as exc:
    st.sidebar.warning(
        f"⚠️ Service unreachable  \n"
        f"`{exc}`  \n"
        "Make sure Headless Bob is running."
    )
    # Allow continued use with demo mode notice
    st.sidebar.info("Running in **offline demo mode** – REST calls will fail gracefully.")

st.sidebar.divider()

# ── Refresh / create thread controls ────────────────────────────────────────

col_r, col_n = st.sidebar.columns([1, 1])
if col_r.button("🔄 Refresh", use_container_width=True, help="Reload thread list"):
    try:
        st.session_state.threads = hb.list_threads()
        st.session_state.last_error = ""
    except Exception as exc:
        st.session_state.last_error = str(exc)
    st.rerun()

if col_n.button("➕ New", use_container_width=True, help="Create a new thread"):
    try:
        ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M")
        thread = hb.create_thread(f"Thread {ts}")
        st.session_state.threads = hb.list_threads()
        st.session_state.active_thread_id = thread.id
        st.session_state.active_thread_title = thread.title
        st.session_state.chat_history = []
        st.session_state.workspace_files = []
        st.session_state.last_error = ""
    except Exception as exc:
        st.session_state.last_error = str(exc)
    st.rerun()

# ── Thread list ──────────────────────────────────────────────────────────────

st.sidebar.subheader("Conversations")

# Load threads on first visit
if not st.session_state.threads:
    try:
        st.session_state.threads = hb.list_threads()
    except Exception:
        pass

threads = st.session_state.threads
if threads:
    for t in threads:
        label = f"💬 {t.title[:30]}{'…' if len(t.title) > 30 else ''}"
        badge = f"  ({t.message_count} msgs)" if t.message_count else ""
        is_active = t.id == st.session_state.active_thread_id

        btn_key = f"thread_{t.id}"
        if st.sidebar.button(
            f"{'▶ ' if is_active else ''}{label}{badge}",
            key=btn_key,
            use_container_width=True,
            type="primary" if is_active else "secondary",
        ):
            st.session_state.active_thread_id = t.id
            st.session_state.active_thread_title = t.title
            # Load message history for this thread
            try:
                messages = hb.list_messages(t.id)
                st.session_state.chat_history = [
                    {
                        "role": m.get("role", "user"),
                        "content": m.get("content", ""),
                        "meta": m,
                    }
                    for m in messages
                ]
                st.session_state.workspace_files = hb.list_workspace_files(t.id)
            except Exception as exc:
                st.session_state.last_error = str(exc)
            st.rerun()
else:
    st.sidebar.info("No threads yet — click ➕ New to start.")

# ── Delete thread ─────────────────────────────────────────────────────────────

if st.session_state.active_thread_id:
    st.sidebar.divider()
    if st.sidebar.button(
        "🗑️ Delete current thread",
        use_container_width=True,
        type="secondary",
        help="Permanently delete this thread and its workspace",
    ):
        try:
            hb.delete_thread(st.session_state.active_thread_id)
            st.session_state.active_thread_id = None
            st.session_state.active_thread_title = ""
            st.session_state.chat_history = []
            st.session_state.workspace_files = []
            st.session_state.threads = hb.list_threads()
        except Exception as exc:
            st.session_state.last_error = str(exc)
        st.rerun()

# ---------------------------------------------------------------------------
# Main panel
# ---------------------------------------------------------------------------

# ── Header ──────────────────────────────────────────────────────────────────

st.title("🤖 Headless Bob — AI-Powered Automation Demo")
st.markdown(
    """
    This demo connects to a running [**Headless Bob**](https://github.com/ibm-self-serve-assets/building-blocks/tree/main/ai/ai-engineering/headless-bob)
    service and drives IBM Bob Shell via its REST API.  
    Create a thread, type any task or question, and watch Bob respond in real time.
    """
)

if st.session_state.last_error:
    st.error(f"Last error: {st.session_state.last_error}")

# ── No active thread placeholder ────────────────────────────────────────────

if not st.session_state.active_thread_id:
    st.info("👈 Select or create a thread in the sidebar to begin.")
    st.markdown("### What can you ask Bob?")
    st.markdown(
        """
        | Example prompt | What Bob does |
        |---|---|
        | `Explain what Headless Bob is` | Knowledge / explanation |
        | `Write a Python function to parse JSON` | Code generation |
        | `Create a file hello.txt with Hello World` | File creation in workspace |
        | `List all files in the workspace` | Tool-use / file browsing |
        | `What are the current date and time?` | Simple query |
        """
    )
    st.stop()

# ── Active thread header ─────────────────────────────────────────────────────

col_title, col_rename = st.columns([4, 1])
col_title.subheader(f"💬 {st.session_state.active_thread_title}")

with col_rename:
    with st.popover("✏️ Rename"):
        new_title = st.text_input("New title", value=st.session_state.active_thread_title)
        if st.button("Save", key="rename_save"):
            try:
                updated = hb.rename_thread(st.session_state.active_thread_id, new_title)
                st.session_state.active_thread_title = updated.title
                # Refresh thread list to show updated name
                st.session_state.threads = hb.list_threads()
            except Exception as exc:
                st.error(str(exc))
            st.rerun()

st.divider()

# ── Chat history ─────────────────────────────────────────────────────────────

chat_area = st.container()
with chat_area:
    for entry in st.session_state.chat_history:
        role = entry["role"]
        content = entry["content"]
        meta = entry.get("meta", {})

        if role == "user":
            with st.chat_message("user"):
                st.markdown(content)
        else:
            with st.chat_message("assistant", avatar="🤖"):
                st.markdown(content)
                # Show run metadata as an expander if available
                run_id = meta.get("run_id")
                if run_id:
                    with st.expander("📊 Run details", expanded=False):
                        try:
                            run = hb.get_run(run_id)
                            c1, c2, c3, c4 = st.columns(4)
                            c1.metric("Status", run.status)
                            c2.metric("Duration", f"{run.duration_ms} ms")
                            c3.metric("Tokens", str(run.total_tokens))
                            c4.metric("Tool calls", str(run.tool_calls))
                        except Exception as exc:
                            st.caption(f"Could not load run stats: {exc}")

# ── Streaming placeholder ────────────────────────────────────────────────────

streaming_placeholder = st.empty()

# ── Workspace files panel ─────────────────────────────────────────────────────

if st.session_state.workspace_files:
    with st.expander(f"📁 Workspace files ({len(st.session_state.workspace_files)})", expanded=False):
        for wf in st.session_state.workspace_files:
            col_path, col_dl = st.columns([3, 1])
            col_path.code(wf.path)
            if col_dl.button("⬇️ Download", key=f"dl_{wf.path}"):
                try:
                    content_bytes = hb.download_workspace_file(
                        st.session_state.active_thread_id, wf.path
                    )
                    st.download_button(
                        label=f"Save {Path(wf.path).name}",
                        data=content_bytes,
                        file_name=Path(wf.path).name,
                        key=f"save_{wf.path}",
                    )
                except Exception as exc:
                    st.error(str(exc))

# ── Chat input ────────────────────────────────────────────────────────────────

st.divider()

col_mode, col_input = st.columns([1, 4])
with col_mode:
    bob_mode = st.selectbox(
        "Bob mode",
        options=["agent", "ask", "plan"],
        index=0,
        help="Select the Bob operating mode for this message",
    )

prompt = st.chat_input("Ask Bob anything, or give it a task…")

if prompt:
    thread_id = st.session_state.active_thread_id

    # Append the user message immediately to the chat history
    st.session_state.chat_history.append({
        "role": "user",
        "content": prompt,
        "meta": {},
    })

    # Show user message right away
    with chat_area:
        with st.chat_message("user"):
            st.markdown(prompt)

    # ── Send to Headless Bob and stream the response ─────────────────────────
    try:
        run = hb.send_message(thread_id, prompt, mode=bob_mode)
        full_response = ""
        run_id = run.run_id

        with streaming_placeholder.container():
            with st.chat_message("assistant", avatar="🤖"):
                stream_box = st.empty()
                stream_box.markdown("_Bob is thinking…_")

                # Consume SSE stream from the run events endpoint
                events_url = run.events_url or f"/api/v1/runs/{run_id}/events"
                for event in hb.stream_events(events_url):
                    # Real SSE event types from the Headless Bob service:
                    #   run.created, run.in-progress, run.completed, run.failed
                    #   message.created, message.part, message.completed
                    etype = event.get("type", "")

                    if etype == "message.part":
                        # Incremental content delta — the live streaming token
                        delta = event.get("part", {}).get("content", "")
                        full_response += delta
                        stream_box.markdown(full_response + "▌")

                    elif etype == "message.completed":
                        # Full assembled message — use as authoritative text
                        msg = event.get("message", {})
                        parts = msg.get("parts", [])
                        text = "".join(p.get("content", "") for p in parts)
                        if text:
                            full_response = text
                        stream_box.markdown(full_response + "▌")

                    elif etype == "run.completed":
                        # Run finished successfully — finalise display
                        run_obj = event.get("run", {})
                        if not full_response:
                            # Extract from output as fallback
                            for out in run_obj.get("output", []):
                                for part in out.get("parts", []):
                                    full_response += part.get("content", "")
                        stream_box.markdown(full_response)
                        break

                    elif etype == "run.failed":
                        # Run ended with an error
                        err_msg = event.get("run", {}).get("error", "Run failed")
                        stream_box.error(f"Run error: {err_msg}")
                        full_response = f"⚠️ Error: {err_msg}"
                        break

                    elif etype == "error":
                        # Service-level error event
                        err = event.get("error", {})
                        err_msg = err.get("message", str(event))
                        stream_box.error(f"Error: {err_msg}")
                        full_response = f"⚠️ Error: {err_msg}"
                        break

                # Finalise display
                if full_response:
                    stream_box.markdown(full_response)
                else:
                    # Fallback: poll for the completed run
                    for _ in range(30):
                        time.sleep(1)
                        final_run = hb.get_run(run_id)
                        if final_run.status in ("completed", "failed", "cancelled"):
                            full_response = final_run.last_message or "(no response)"
                            stream_box.markdown(full_response)
                            break

        # Append assistant response to chat history
        st.session_state.chat_history.append({
            "role": "assistant",
            "content": full_response,
            "meta": {"run_id": run_id},
        })

        # Refresh workspace file list after the run completes
        try:
            st.session_state.workspace_files = hb.list_workspace_files(thread_id)
        except Exception:
            pass

        # Clear the streaming placeholder and re-render the full history
        streaming_placeholder.empty()
        st.rerun()

    except EnvironmentError as exc:
        st.error(str(exc))
    except Exception as exc:
        st.error(f"Failed to communicate with Headless Bob: {exc}")
        st.info(
            "Verify that HEADLESS_BOB_URL and HEADLESS_BOB_TOKEN are set correctly "
            "and that the Headless Bob service is running."
        )
